## Sylvain SCHMITT
## 21/07/2021

ressources: "ressources.genologin.yaml"

# data
refdir: "../data/hetre/genome"
reference: "Fagus_sylvatica_v3"
libdir: "../data/hetre/reads/"

# libraries
samples: ["mutant", "revertant"]
comps: ["mutant_vs_revertant", "revertant_vs_mutant"]
