## Sylvain SCHMITT
## 28/04/2021

# Ressources
ressources: "ressources.local.yaml"

# data
refdir: "data/generated"
reference: "Qrob_PM1N_2Chr_7k"
libdir: "data/generated"

# results
vcfs: ["test1_vs_test2"]
