## Sylvain SCHMITT
## 28/04/2021

# Ressources
ressources: "ressources.genologin.yaml"

# data
refdir: "../generateMutations/results/reference/"
reference: "Qrob_PM1N"
libdir: "../generateMutations/results/reads/"
mutdir: "../generateMutations/results/mutations/"
callers: ["mutect2", "freebayes", "gatk", "strelka2", "varscan", "somaticsniper", "muse"]
