## Sylvain SCHMITT
## 28/04/2021

# Ressources
ressources: "ressources.genologin.yaml"

# data
refdir: "../generateMutations/results/reference/"
reference: "Qrob_PM1N_7k_Qrob_Chr01"
snps: "Qrob_PM1N_7k_Qrob_Chr01_snps.vcf"
libdir: "../data/"
