## Sylvain SCHMITT
## 28/04/2021

# Ressources
ressources: "ressources.genologin.yaml"

# data
refdir: "data"
reference: "Qrob_PM1N"
libdir: "/home/sschmitt/save/swiss/raw"

# results
vcfs: ["upper_vs_lower", "lower_vs_upper"]
