## Sylvain SCHMITT
## 21/07/2021

ressources: "ressources.genologin.yaml"

# data
refdir: "../data/sixto/genome"
reference: "Sru_HiFiasm.haplotype1"
libdir: "../data/sixto/reads/"
intervals: "../data/sixto/genome/intervals"

# libraries
hz: ["T1", "T2", "T3", 
     "B1L1", "B1L2", "B1L3",
     "C1S1", "C1S2", "C1S3", "C3L1", "C3L2", "C3L3",
     "E2L1", "E2L2", "E2L3", "E4S1", "E4S2", "E4S3",
     "F2S2", "F2S3", "F2S4",
     "I1L1", "I1L2", "I1L3", "I2S2", "I2S3", "I2S5"]
cambium: ["T1", "T2", "T3"]
cambium_comp: ["T1_vs_T2", "T1_vs_T3", "T2_vs_T1", "T2_vs_T3", "T3_vs_T1", "T3_vs_T2"]
cambium_ref: "T1"
leaf: ["B1L1", "B1L2", "B1L3",
       "C1S1", "C1S2", "C1S3", "C3L1", "C3L2", "C3L3",
       "E2L1", "E2L2", "E2L3", "E4S1", "E4S2", "E4S3",
       "F2S2", "F2S3", "F2S4", 
       "I1L1", "I1L2", "I1L3", "I2S2", "I2S3", "I2S5"]
leaf_cov: "B1L3"
