## Sylvain SCHMITT
## 21/07/2021

ressources: "ressources.genologin.yaml"

# data
refdir: "../data/angela/genome"
reference: "Dgu_HS1_HYBRID_SCAFFOLD"
libdir: "../data/angela/reads/"
intervals: "../data/angela/genome/intervals_dag"

# libraries
hz: ["T2", "T3", "DS2"]
cambium: ["T2", "T3"]
cambium_comp: ["T2_vs_T3"]
cambium_ref: "T2"
leaf: ["DS2"]
leaf_cov: "DS2"
