## Sylvain SCHMITT
## 28/04/2021

# Ressources
ressources: "ressources.genologin.yaml"

# data
refdir: "data/swiss"
reference: "Qrob_PM1N"
libdir: "data/swiss"

# results
vcfs: ["upper_vs_lower", "lower_vs_upper"]

# filter
normalAC: 0
mutationsAC: 10
singleDP: 100
