## Sylvain SCHMITT
## 21/07/2021

ressources: "ressources.genologin.yaml"

# data
refdir: "../data/angela/genome"
reference: "Dgu_HS1_HYBRID_SCAFFOLD"
hz: ""
# libdir: "../data/angela/reads/"
libdir: "../data/angela/dummyreads/"
