## Sylvain SCHMITT
## Sylvain SCHMITT
## 28/04/2021

# Ressources
ressources: "ressources.genologin.yaml"

# data
refdir: "data/bordeaux"
reference: "Qrob_PM1N"
libdir: "data/bordeaux"

# results
vcfs: ["L1_vs_L2", "L2_vs_L1"]
