## Sylvain SCHMITT
## 21/07/2021

ressources: "ressources.genologin.yaml"

# paths
refdir: "../data/hetre/genomes/"
libdir: "../data/hetre/reads/"

# samples
references: ["Fagus_sylvatica_v3", "Fagus_sylvatica_mutant_v0", "Fagus_sylvatica_revertant_v0"]
samples: ["mutant", "revertant"]
comps: ["mutant_vs_revertant", "revertant_vs_mutant"]
