## Sylvain SCHMITT
## 21/07/2021

ressources: "ressources.genologin.yaml"

# data
refdir: "../data/sixto/genome"
reference: "Sru_HiFiasm.haplotype1"
libdir: "../data/sixto/reads/"
intervals: "../data/sixto/genome/intervals_dag"

# libraries
hz: ["T1", "T2", "B1L1"]
cambium: ["T1", "T2"]
cambium_comp: ["T1_vs_T2"]
cambium_ref: "T1"
leaf: ["B1L1"]
leaf_cov: "B1L1"
