__default__:
  jobname: "default"
  mem: "16G"
  cpus: 4
  time: "48:00:00"

## Reference ## 

samtools_faidx_split:  
  jobname: "samtools_faidx_split"
  mem: "4G"
  cpus: 1
  time: "01:00:00"

bwa_index:
  jobname: "bwa_index"
  mem: "4G"
  cpus: 1
  time: "01:00:00"
  
samtools_faidx:
  jobname: "samtools_faidx"
  mem: "4G"
  cpus: 1
  time: "01:00:00"
  
gatk_dict:
  jobname: "gatk_dict"
  mem: "4G"
  cpus: 1
  time: "01:00:00"

## Reads ##

cp_reads:
  jobname: "cp_reads"
  mem: "4G"
  cpus: 1
  time: "01:00:00"
  
fastqc:
  jobname: "fastqc"
  mem: "16G"
  cpus: 4
  time: "01:00:00"

trimmomatic:
  jobname: "trimmomatic"
  mem: "16G"
  cpus: 4
  time: "10:00:00"

## Alignments ##

bwa_mem:
  jobname: "bwa_mem"
  mem: "32G"
  cpus: 8
  time: "96:00:00"
  
samtools_view:
  jobname: "samtools_view"
  mem: "4G"
  cpus: 1
  time: "01:00:00"
  
samtools_sort:
  jobname: "samtools_sort"
  mem: "4G"
  cpus: 1
  time: "01:00:00"

samtools_index:
  jobname: "samtools_index"
  mem: "4G"
  cpus: 1
  time: "01:00:00"
  
gatk_markduplicates:
  jobname: "gatk_markduplicates"
  mem: "100G"
  cpus: 1
  time: "48:00:00"
  
samtools_view_md:
  jobname: "samtools_view_md"
  mem: "4G"
  cpus: 1
  time: "01:00:00"
  
samtools_index_md:
  jobname: "samtools_index_md"
  mem: "16G"
  cpus: 4
  time: "01:00:00"
  
## Mutations ##

strelka2:
  jobname: "strelka2"
  mem: "200G"
  cpus: 20
  time: "96:00:00"
  
## QC ##

samtools_stats:
  jobname: "samtools_stats"
  mem: "4G"
  cpus: 1
  time: "01:00:00"
  
qualimap:
  jobname: "qualimap"
  mem: "16G"
  cpus: 4
  time: "01:00:00"
  
multiqc:
  jobname: "multiqc"
  mem: "4G"
  cpus: 1
  time: "01:00:00"
