---
title: A roadmap for plant mutation detection tools with variable sequencing depth and allele frequency using two reproducible pipelines
author: (**Alphabetic**) Myriam Heuertz, Thibault leroy, Sylvain Schmitt, Niklas Tysklind
date: '`r Sys.Date()`'
output:
  bookdown::html_document2:
    number_sections: false
    toc: true
    toc_float: yes
  bookdown::pdf_document2:
    template: ./template/templateSuppMatMolEcol.tex
    number_sections: false
    toc: false
    keep_tex: true
  bookdown::word_document2:
    reference_docx: ./template/template.docx
linestretch: 1.5
csl: /home/sylvain/Documents/Bibliography/csl/molecol.csl
bibliography: /home/sylvain/Documents/Bibliography/library.bib
link-citations: yes
always_allow_html: yes
---


```{r config, message=FALSE, warning=FALSE, include=FALSE}
rm(list = ls()); invisible(gc())
library(knitr)
library(tidyverse)
library(bayesplot)
theme_set(bayesplot::theme_default())
opts_chunk$set(echo = F, message = F, warning = F, 
               fig.height = 6, fig.width = 8,
               cache = T, cache.lazy = F)
stats <- read_tsv("stats.experiment4.tsv") %>% 
  group_by(caller, N, R, AF, C) %>% 
  summarise_at(c("FN", "FP", "TP", "Precision", "Recall"), mean, na.rm = T) %>% 
  mutate(caller = recode(caller,    
                         "mutect2" = "Mutect2", 
                         "freebayes" = "freebayes", 
                         "gatk" = "GATK", 
                         "strelka2" = "Strelka2", 
                         "somaticsniper" = "Somatic Sniper", 
                         "muse" = "MuSE",
                         "varscan" = "VarScan"
  )) %>% 
  ungroup()
```


```{r fig1}
stats %>% 
  reshape2::melt(c("caller", "FN", "FP", "TP", "Precision", "Recall"),
                 variable.name = "parameter", value.name = "parameter.value") %>% 
  reshape2::melt(c("caller", "parameter", "parameter.value"),
                 variable.name = "metric", value.name = "metric.value") %>% 
  filter(metric %in% c("Precision", "Recall")) %>% 
  filter(parameter != "N") %>% 
  mutate(parameter = recode(parameter, "N" = "Number\nof mutations", "R" = "Transition\nTransversion Ratio",
                            "AF" = "Allele\nFrequency", "C" = "Coverage")) %>% 
  ggplot(aes(as.factor(parameter.value), metric.value, col = caller, fill = caller)) +
  geom_boxplot(alpha = 0.3) +
  facet_grid(metric ~ parameter, scales = "free") +
  theme(legend.position = "bottom", axis.title = element_blank()) +
  scale_color_discrete("") +
  scale_fill_discrete("")
```

```{r fig2}
read_tsv("stats.experiment4.tsv") %>%
  filter(C %in% c(50, 150)) %>% 
  mutate(C = recode(C, "50" = "low coverage (50X)", "150" = "high coverage (150X)")) %>% 
  select(caller, C, AF, Recall, Precision) %>% 
  reshape2::melt(c("caller", "C", "AF")) %>% 
  group_by(caller, C, AF, variable) %>% 
  na.omit() %>% 
  mutate(m = mean(value), q5 = quantile(value, 0.05), q95 = quantile(value, 0.95)) %>% 
  ggplot(aes(x = AF, col = caller, fill = caller)) +
  geom_ribbon(aes(ymin = q5, ymax = q95), alpha = 0.3, col = NA) +
  geom_line(aes(y = m)) +
  geom_point(aes(y = value), alpha = 0.5) +
  facet_grid(variable ~ C) +
  xlab("Allele frequency") +
  ylab("") +
  scale_color_brewer("", palette = "Paired") +
  scale_fill_brewer("", palette = "Paired")
```

```{r fig2}
read_tsv("stats.experiment4.tsv") %>%
  filter(C %in% c(25, 75, 150)) %>% 
  mutate(C = paste0(C, "X")) %>% 
  mutate(C = factor(C, levels = c("25X", "75X", "150X"))) %>% 
  select(caller, C, AF, Recall, Precision) %>% 
  reshape2::melt(c("caller", "C", "AF")) %>% 
  group_by(caller, C, AF, variable) %>% 
  na.omit() %>% 
  mutate(m = mean(value), q5 = quantile(value, 0.05), q95 = quantile(value, 0.95)) %>% 
  ggplot(aes(x = AF, col = caller, fill = caller)) +
  geom_ribbon(aes(ymin = q5, ymax = q95), alpha = 0.3, col = NA) +
  geom_line(aes(y = m)) +
  geom_point(aes(y = value), alpha = 0.5) +
  facet_grid(C ~ variable) +
  xlab("Allele frequency") +
  ylab("") +
  scale_color_brewer("", palette = "Paired") +
  scale_fill_brewer("", palette = "Paired") +
  theme(legend.position = "bottom")
```


